### Change the IP address below to your PC's IP address. Remain the port number 3000 unchanged
@baseUrl = http://localhost:5001/utm-xchange-yeasin/us-central1/utmXchange

### CheckList 1 : Define the HTTP Request to get the list of hotels
GET {{baseUrl}}/hotels

###  Getting a hotels of given id
GET {{baseUrl}}/hotels/ZHuqhz0643fraa8quS4W

### hotels 5 : Define the HTTP Request to update the status of a given hotels (whether is completed or not)
PATCH {{baseUrl}}/hotels/ZHuqhz0643fraa8quS4W
Content-Type: application/json

{
    "telephone": "2O-009009"
}

### hotels 6 : Define the HTTP Request to create a new hotels
POST {{baseUrl}}/hotels
Content-Type: application/json

{
    "name": "New hotels",
    "telephone": "000099900",
    "address": "no address please",
    "personCharge": "Dont ask me please"
}

### hotels 7 : Define the HTTP Request to delete a given hotels
DELETE {{baseUrl}}/hotels/ZHuqhz0643fraa8quS4W